### PR TITLE
Broke up db_api.js into several model files

### PR DESCRIPTION
**Pull request by ttocskcaj**
Lots of things changed here with how the database works. The main idea was to split the db_api.js file up before it becomes too big.

I created a couple of model files for Genres and Venues: 
 - GenreModel.js
 - VenueModel.js
Each one of these holds an object to model the real life object and also holds methods to CRUD data in the database. I also changed how model objects are created and passed around a little bit to suit this method.

Also updated tests to suit.

Have a look and tell me if you're happy with this way, otherwise, I can just rollback.

### CODE REVIEW

**Comment by lxdnz254** [comment]
I see what you were trying to achieve, but it has broken everything. A rollback might be necessary here.
Does it work on your local machine?

**Comment by lxdnz254** [comment]
index.js needs the db.initialise() function, this ensures on startup that local or remote databases will have the required data (i.e this is how we would implement a database backup and restart if necessary)

**Comment by lxdnz254** [comment]
Ooops, neo4j wasn't running properly, that what was throwing errors.

**Review by lxdnz254 — APPROVED** [review]
I'm happy with db model.
`db.initialise()` will be a useful tool for backups and ensuring we all have the right data locally.
Note to ourselves to check for response changes on clientside.

**Comment by ttocskcaj** [comment]
I was thinking it would be a good idea to set up a new script to create the database data. Could use it for backups etc as well.
What do you think?

_Sent from my Samsung GT-I9505 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by lxdnz254** [comment]
I think that is something to look at once we have aĺl the data going in. The focus should be getting venue and artists logged in and submitting details, then displaying the details.

**Pull request merged**
