### PR TITLE
Lots of refactoring

### PR DESCRIPTION
**Pull request by ttocskcaj**
- Expanded and added some comments in index.js
- Split up routing for API and client side files.
- Changed routes for API to use a syntax such as /api/genres
- Created express controllers for genres and venues and implemented them
- Changed angular maincontroller to use new URLs.
- Updated tests to use new URLs and ran tests. Everything seems fine.

### CODE REVIEW

**Comment by lxdnz254** [comment]
I'll check it out, thanks Jack

**Comment by lxdnz254** [comment]
POST api/venue does not work, in test yes, but with webpage NO post action. Which is why I had set that as a GET /send_venue operation

**Comment by ttocskcaj** [comment]
Won't we be using Angular/ajax for most API requests in the future though?

**Comment by ttocskcaj** [comment]
As in, shouldn't maincontroller.js $http.post() be able to do a post request to that url

**Comment by lxdnz254** [comment]
Yes, all the other methods are fine, but the post method is not sending the
parameters.
The api accepts and returns arrays of objects.
 Client side creates the object or unravels it for use...

**Comment by lxdnz254** [comment]
Me and Jack had to debug the heck out of it, but success!

**Pull request merged**
