### PR TITLE
Moved DB initilise to its own migrate script

### PR DESCRIPTION
**Pull request by ttocskcaj**
Run
```
npm run migrate
```

### CODE REVIEW

**Review by lxdnz254 — CHANGES_REQUESTED** [review]
That's a great implementation.
 Update the README.md file to explain how that works, and Heroku will need to run the migrate file on a push to production.

**Comment by ttocskcaj** [comment]
Any idea how to get Heroku to do that? haha

**Comment by lxdnz254** [comment]
I think that maybe right. The file that tells heroku to run `node index.js` can also run scripts too

**Comment by ttocskcaj** [comment]
Check out that update. Any idea how to get it to run process.exit() AFTER all those transactions are done?
It's easy when there's only one as you can just put it in
```javascrtipt
resultPromise.then(result => {
    process.exit();
});
```
but that won't work when there's 3 promises..

**Comment by lxdnz254** [comment]
Got that working, but I noticed that the venues in migrateVenues() only link the relationship to Genres, which is good methodology, but we will need to change api/venue (or artist) to fill the genre[] with the relationship node [LIKES_GENRES]  instead of the venue.node attribute 'genre'

**Comment by lxdnz254** [comment]
I think that wraps that up. I'm not sure about having process.exit() at end of migrateVenues(). If migrateArtists() takes longer or is called after migrateVenues() then it might cause errors.. Sometimes javascript calls functions back to front dependings on process availability 
i.e 
```
function callFunctions() {
function1();
function2();
}
```
may call `function2()` then `function1()`

**Comment by ttocskcaj** [comment]
I had that exact problem. Since my neo4j is running on my Linux machine it was exiting the program before it got a response from the server.
We either need to do all migrations in one transaction, or figure a way to exit the script once all 3 finish.
Asynchronous is handy sometimes, but it's really annoying as well haha

Is there any need to have the venue.genre attribute?

_Sent from my Samsung GT-I9505 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by lxdnz254** [comment]
I'll write a big transaction when get home and see how that goes, I've got it mainly worked out in my head

**Comment by lxdnz254** [comment]
As a note, even though the Promise(s) may not have resolved, the transaction(s) would have taken place, so the database should have had been updated (migrated). The Promise is only a callback to the data that was placed on the database

**Comment by ttocskcaj** [comment]
No data was entered. I'm not sure why, but I think it's probably just because my desktop that node is running on is faster than the server than neo4j is running on.

**Comment by lxdnz254** [comment]
It must be connecting otherwise it would throw errors (on node). Did the nodes already exist in database? If they did then a merge wouldn't take place and no new data would be created

**Comment by ttocskcaj** [comment]
Nah it was an empty database. It's working now that they're chained to fire one after the other though.

I think node queues each method call and then processes them or something. 
System.exit() obviously gets processed before (or quicker) than the database stuff. 

Rule of thumb for JS: If something needs to be executed after something else, do it in a callback.

**Pull request merged**
