### PR TITLE
Fixed search

### LINKED ISSUE #36: Search expects genre
A small issue to solve.
`/api/search` expects a "genre" variable, we need to set a default if no "genre" is selected.
image

Should be a relatively simple fix.

### PR DESCRIPTION
**Pull request by ttocskcaj**
Fixes #36 and adds ability to search for venues by location

### CODE REVIEW

**Comment by lxdnz254** [comment]
Add a test to the test suite

**Comment by lxdnz254** [comment]
Change the 'it' descriptions to match what the test is doing I.e "genre query should return an array"

**Review by lxdnz254 — APPROVED** [review]
Good implementation in the back-end, now we need a front-end location selector
 I have merged this branch into PR #37 so conflicts wont result

**Comment by lxdnz254** [comment]
What about displaying a message to the end user when status 501 is returned, i.e. "No search query entered!!"

**Comment by ttocskcaj** [comment]
That may not be needed. We could just use js validation to check if there's something in the form before it's allowed to be submitted.
I.E. Check before it's sent, not after a message is returned.

I don't think there's a need for the API to return a message other than the HTTP status code. Anyone not using the form to submit a search is using it wrong anyway 😆

**Comment by lxdnz254** [comment]
Yep, validate the search data before sending. I.e. pressing search button with nothing selected will result in the message being displayed client side, no http call to server

**Comment by ttocskcaj** [comment]
I have a cool js validation library I wrote for an old project somewhere. We can adapt that if you want?

**Comment by lxdnz254** [comment]
Yeah cool, existing libraries are great, less code writing.. does it extend to form validation as that would be useful too

**Comment by ttocskcaj** [comment]
Yeah, that's what I was meaning. It's for form validation not server-side. It's a jQuery plugin. I'll dig it up later

**Comment by lxdnz254** [comment]
All good then, merge away

**Pull request merged**
