### PR TITLE
Added artists to API

### PR DESCRIPTION
**Pull request by ttocskcaj**
API Only, no client stuff yet.

### CODE REVIEW

**Comment by lxdnz254** [comment]
Cool, that'll help out Laurence.
I've almost sorted the search bar in to a directive, just trying to bring it api/genre back down to one call

**Comment by ttocskcaj** [comment]
Sweet as. It'll display on mobile fine as long as you don't use any of the navbar classes (bootstrap hides their content on mobile)
Create a new "barlike" class if you want, or I can.

**Comment by lxdnz254** [comment]
Yeah I've got that bit running, but aiming for a stand alone search bar that displays different options for various pages is a bit more complex

**Comment by lxdnz254** [comment]
I'm happy for you to merge that update. 
After milking I'll keep playing around with search bar directive, I'm aiming for `<searchbar page="venues">` and that will load only search options for venues etc

**Pull request merged**
