### PR TITLE
Venue list directive

### PR DESCRIPTION
**Pull request by EuroWhisper**
I can think of a couple of potential reasons why it won't work:
1) Something may need to be added on the server-side to allow venue.html template to be loaded? I didn't see an XHR request for it in Chrome's dev tools and I didn't see anything about it being accessed in the Node CMD either.
2) Regardless if #1 is true or not. Do directives expect to receive the scope from the controller that is the context in which the directive is being used? If so then how to go about getting the directive to use the data from rootscope instead, which seems to be where the venues are stored after being loaded from the server?

Thanks guys!

### CODE REVIEW

**Comment by lxdnz254** [comment]
I have been working through this problem too with the angular coverflow implementation as well. I haven't looked at running code yet, but I think the problem lies in the directive trying to load 'response' which is not there so causes error 'response is undefined'. Am I correct?

A solution (as yet unresolved) is to create a watcher on the 'response' variable that will only run the directive code if it exists.

**Comment by lxdnz254** [comment]
First fix coming -- gulpfile needs to see directive folder to load into package

**Comment by EuroWhisper** [comment]
Thanks for that. So I was sort of on the right track with question 1. By the way, is there something else that needs to be added before the venue.html template in the directives folder can be accessed?

**Comment by lxdnz254** [comment]
I'm working through that at the moment. I think it's something to do with
the routing. If I set replace to false then I get continuous loop of whole
page.
From what I can see, venue.html is not being loaded, I'm just waiting for
loop to stop then I can have a crack at routing

**Comment by lxdnz254** [comment]
yes its defiantley the routing,
I altered the directive to read:
`template: 
		'<div class="col-xs-12 col-md-6 col-lg-3">' +
			'<div class="card">' +
				'<h4>{{responseVenue.name}}</h4>' +
				'<ul>' +
					'<li>Location: {{responseVenue.location}}</li>' +
					'<li>Capacity: {{responseVenue.capacity}}</li>' +
				'</ul>' +
			'</div>' +
		'</div>'`

instead of `templateUrl` (which is the html file written in the directive instead of a separate file )and it all works fine.

**Comment by lxdnz254** [comment]
I will try the $routeProvider to make a link

**Comment by EuroWhisper** [comment]
Would you be able to commit it as you've got it working now, so I can check it out please? I actually did the same thing, trying to use template instead of templateUrl and still got an AngularJS compile error to do with venue.html even though I removed templateUrl from the directive.

**Comment by lxdnz254** [comment]
Sorry about the wait, I was trying a few routes out, but here is a working version

**Comment by lxdnz254** [comment]
Genres work as well,
I also read that templateUrl: does not like  in the html file as it reads it as another div, so I removed the comment from venue.html, while we troubleshoot

**Comment by EuroWhisper** [comment]
Thanks for that. Very strange, you made the same change that I did but it didn't work when I did it. Yet when I pulled your code it worked fine. Could it have been some weird caching thing?

**Comment by EuroWhisper** [comment]
Looks like it is some sort of cache issue, when I make changes to venue-list.js they don't show up when I close Node, then "node index.js" again and ctrl + f5 the page. How should I go about starting and stopping the server to avoid stuff like this?

**Comment by lxdnz254** [comment]
Before you run anything `package.min.js` needs to be built with `gulp scripts`. The best practice is to open a console in your development folder and run `gulp watch` , that ensures all changes get built automatically 
You should also open another console and launch `npm test watch` which will run the test suite on a file save, if you break anything you can see straight away and revert or fix. It is also best practice to write a test function for any server calls that get made. Test Driven Development  (TDD) is an integral part of Agile development

**Review by lxdnz254 — APPROVED** [review]
Solved the issues:
Points for future development reference
1. `gulp scripts` & `gulp less` must be run after altering code on client-side, best way to do this is having a console running `gulp watch` which will always build package.min.js after any code changes.
2. Any thing that needs to be "seen" in a browser must be placed inside the "/views/" folder
3. `npm start` or `node index.js` only need to be restarted when server-side code is altered
4. `npm test watch` and the test suite are your friends, use it to ensure the app remains stable.

**Comment by EuroWhisper** [comment]
Thanks for explaining that, Alex. Makes sense to me now. Is it alright to merge the pull request now?

**Comment by lxdnz254** [comment]
Yep. Merge is ok. I'll do now then resolve the coverflow PR

**Pull request merged**
