### PR TITLE
Jack

### PR DESCRIPTION
**Pull request by ttocskcaj**

### CODE REVIEW

**Comment by lxdnz254** [comment]
Conflict in routes.js Jack branch the new version?

**Comment by lxdnz254** [comment]
Index.js did you add in the try catch?

**Comment by ttocskcaj** [comment]
Yea. I thought I was up-to-date with github when I started. My bad. Fixed it now.

**Comment by lxdnz254** [comment]
That's a bit better. Now I'll look at the code

**Comment by lxdnz254** [comment]
Is it meant to display anything on web page?

**Comment by lxdnz254** [comment]
I'm happy with the code, but it should have been a good idea to add at least a message in the body of index.html to indicate the client was working properly. Did you get the message from Heroku about node.js DoS attacks, upgrade node to above 8.1.4 to fix

**Comment by ttocskcaj** [comment]
Nope. index.html is empty now, and I moved your stuff to test.html
`<!DOCTYPE html>
<html lang="en_GB">
<head>
    <meta charset="UTF-8">

    <link rel="stylesheet" href="/css/style.css">
    <title>Musician Venue App</title>
</head>
<body>

</body>
</html>`

**Comment by ttocskcaj** [comment]
I mean it's only empty because I'm doing that bit next. I just wanted to push the other stuff first

**Comment by lxdnz254** [comment]
That's all good. I see what you were trying to achieve, each push and
commit should be an improvement in the overall web app, not a backwards
step...

**Comment by lxdnz254** [comment]
So now, pull from the dev branch and then checkout to Jack. Makes sure
you've got the latest code branch... npm install - i ...

**Comment by lxdnz254** [comment]
Or merge you local version branches

**Pull request merged**
