### PR TITLE
Angular coverflow

### PR DESCRIPTION
**Pull request by lxdnz254**
Wrote a directive to simulate cover-flow effect for venues, including searched venues.
Is this the type of effect we are looking for for our search result display?

 Not quite sure how to integrate Laurence's "venue.html" template directive into this, (see branch `venue-directive` ) but will make that a work in progress. I like the idea of editing the venue.html file to change the display output, rather than re-working the directive code.

### CODE REVIEW

**Comment by EuroWhisper** [comment]
Is this just to be used on smaller mobile devices? On iPad sized tablets and screen sizes above that wouldn't it be quicker to browse the venues with a more traditional list or grid style view of the venues? Can't remember if we decided the Tinder style view would just be used for the mobile view or not.

**Comment by ttocskcaj** [comment]
I think the idea was to do this for mobile and a grid or list for larger

_Sent from my Samsung GT-I9505 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by lxdnz254** [comment]
@ttocskcaj you are quite right. I went back and had a look at wireframes on Trello and that is the two design models agreed upon.
So, does this mean that our code base is going to split here, 1 for desktop, 1 for mobile? Or shall we handle different screen sizes or devices implementing different features  (directives/controllers etc) with jQuery calls?
Along the lines of 
`if (desktop) => venue-grid-list 
else if  (small screen mobile) => coverflow`

**Comment by lxdnz254** [comment]
I do think that if we keep the grid-list then the cards must have minimal information on them, and then a user would click/select a card they liked which would then open a larger information card.
We would also need to scale the cards depending on how many search items were returned, 1 or 2 small cards may look very dis-proportionate to the rest of the layout.
If the cards were to grow in size, say adding background images and a bit more detail for the user, then a search return with lots of results would end up with the user having to scroll down the page for a long time (which is the same result as going sideways..)

I think that at this point, we need to sign-off a final design for the display output of one venue/artist (i.e a card) for desktop and mobile, before we can decide how best to display multiple venues/artists
This also involves determining ***all*** the information that needs to be collected (_submission forms_) and stored in the database.

**Comment by ttocskcaj** [comment]
Doesn't angular have a way to show the right template depending on the screen size?

Also, changing the size and details of the cards for different screens is easy with just CSS.

**Comment by lxdnz254** [comment]
Most likely that angular does, or we could write our own..

**Pull request merged**
